// src/constants.js

export const DWD_REGIONS = {
  11: "Schleswig-Holstein und Hamburg",
  12: "Schleswig-Holstein und Hamburg",
  20: "Mecklenburg-Vorpommern",
  31: "Niedersachsen und Bremen",
  32: "Niedersachsen und Bremen",
  41: "Nordrhein-Westfalen",
  42: "Nordrhein-Westfalen",
  43: "Nordrhein-Westfalen",
  50: "Brandenburg und Berlin",
  61: "Sachsen-Anhalt",
  62: "Sachsen-Anhalt",
  71: "Thüringen",
  72: "Thüringen",
  81: "Sachsen",
  82: "Sachsen",
  91: "Hessen",
  92: "Hessen",
  101: "Rheinland-Pfalz und Saarland",
  102: "Rheinland-Pfalz und Saarland",
  103: "Rheinland-Pfalz und Saarland",
  111: "Baden-Württemberg",
  112: "Baden-Württemberg",
  113: "Baden-Württemberg",
  121: "Bayern",
  122: "Bayern",
  123: "Bayern",
  124: "Bayern",
};

// Per-adapter allergen alias maps.
// Each maps raw/localized allergen slugs to canonical keys.
// The global ALLERGEN_TRANSLATION is computed from these at the bottom.

const PP_ALIASES = {
  al: "alder",
  alm: "elm",
  bok: "beech",
  bjork: "birch",
  ek: "oak",
  grabo: "mugwort",
  gras: "grass",
  hassel: "hazel",
  malortsambrosia: "ragweed",
  salg_och_viden: "willow",
};

const DWD_ALIASES = {
  erle: "alder",
  ambrosia: "ragweed",
  esche: "ash",
  birke: "birch",
  buche: "beech",
  hasel: "hazel",
  graser: "grass",
  graeser: "grass",
  beifuss: "mugwort",
  roggen: "rye",
};

const PEU_ALIASES = {
  olive: "olive",
  plane: "plane",
  cypress: "cypress",
  lime: "lime",
  mold_spores: "mold_spores",
  nettle_and_pellitory: "nettle_and_pellitory",
  fungal_spores: "mold_spores",
  grasses: "grass",
  cypress_family: "cypress",
  nettle_family: "nettle_and_pellitory",
  plane_tree: "plane",
  rye: "rye",
  ragweed: "ragweed",
  birch: "birch",
  alder: "alder",
  hazel: "hazel",
  mugwort: "mugwort",
  allergy_risk: "allergy_risk",
  index: "allergy_risk",
};

const KLEENEX_ALIASES = {
  pine: "pine",
  poplar: "poplar",
  poaceae: "poaceae",
  chenopod: "chenopod",
  nettle: "nettle",
  grass_cat: "grass_cat",
  trees_cat: "trees_cat",
  weeds_cat: "weeds_cat",
};

const PLU_ALIASES = {
  sorrel: "sorrel",
  rumex: "sorrel",
  ampfer: "sorrel",
  oseille: "sorrel",
  artemisia: "mugwort",
  betula: "birch",
  bouleau: "birch",
  fagus: "beech",
  hetre: "beech",
  hetra: "beech",
  quercus: "oak",
  eiche: "oak",
  chene: "oak",
  alnus: "alder",
  aulne: "alder",
  fraxinus: "ash",
  frene: "ash",
  chenopodium: "goosefoot",
  goosefoot: "goosefoot",
  gaensefuss: "goosefoot",
  gansefuss: "goosefoot",
  chenopode: "goosefoot",
  poacea: "poaceae",
  graminees: "poaceae",
  corylus: "hazel",
  haselnussstrauch: "hazel",
  noisetier: "hazel",
  plantago: "plantain",
  plantain: "plantain",
  wegerich: "plantain",
  armoise: "mugwort",
};

const ATMO_ALIASES = {
  ambroisie: "ragweed",
  gramine: "grass",
  olivier: "olive",
  pm25: "pm25",
  pm10: "pm10",
  ozone: "ozone",
  no2: "no2",
  so2: "so2",
  dioxyde_d_azote: "no2",
  dioxyde_de_soufre: "so2",
  qualite_globale: "qualite_globale",
};

const GPL_ALIASES = {
  cottonwood: "poplar",
  juniper: "cypress",
  japanese_cedar: "cypress",
  japanese_cypress: "cypress",
  graminales: "grass",
  cypress_pine: "cypress",
};

// GP (svenove/home-assistant-google-pollen) slugified display_name aliases.
// Auto-generated from the Google Pollen API for 35 languages
// by scripts/fetch-gp-translations.js using the card's own slugify().
// Non-Latin scripts are now properly transliterated via any-ascii.
const GP_ALIASES = {
  abedul: "birch",
  aeoch: "ash",
  aerkwid: "ragweed",
  aes: "ash",
  aihao: "mugwort",
  ais: "ash",
  al: "alder",
  aldar: "alder",
  aldr: "alder",
  alibh: "olive",
  aliso: "alder",
  aliv: "olive",
  aliv_mokk: "olive",
  alnos: "alder",
  altr: "alder",
  alun: "hazel",
  ambroisie: "ragweed",
  ambrosia: "ragweed",
  ambrozia: "ragweed",
  ambrozie: "ragweed",
  ambroziya: "ragweed",
  ambrozja: "ragweed",
  amerikai_nyar: "poplar",
  amieiro: "alder",
  amvrosia_artemisifyllos: "ragweed",
  arin: "alder",
  armoise: "mugwort",
  artemisia: "mugwort",
  artemisia_comune: "mugwort",
  as: "ash",
  ask: "ash",
  aulne: "alder",
  aveleira: "hazel",
  avellano: "hazel",
  ayas: "ash",
  bailashu: "ash",
  barc: "birch",
  beifuss: "mugwort",
  beiskambrosia: "ragweed",
  bereza: "birch",
  berk: "birch",
  betula: "birch",
  betulla: "birch",
  bijvoet: "mugwort",
  birk: "birch",
  birke: "birch",
  bjork: "birch",
  borovica: "pine",
  borovice: "pine",
  bouleau: "birch",
  brc: "birch",
  breza: "birch",
  briza: "birch",
  brzoza: "birch",
  butakusa: "ragweed",
  bylica: "mugwort",
  bynkeambrosie: "ragweed",
  cam: "pine",
  caolei: "grass",
  carvalho: "oak",
  cay_bach_duong: "birch",
  cay_duong_tia: "alder",
  cay_go_duong: "poplar",
  cay_lieu_sam_nhat: "cypress",
  cay_oliu: "olive",
  cay_phi: "hazel",
  cay_soi: "oak",
  cay_tan_bi: "ash",
  cay_thong: "pine",
  cedar_jepang: "cypress",
  cedre_du_japon: "cypress",
  cedro_giapponese: "cypress",
  cedro_japones: "cypress",
  cedru_japonez: "cypress",
  chamnamu: "oak",
  chene: "oak",
  chingchuchay: "mugwort",
  chopo: "poplar",
  choupos: "poplar",
  cim: "grass",
  cndnm: "birch",
  co_phan_huong: "ragweed",
  cottonwood: "poplar",
  dab: "oak",
  devdar: "pine",
  disbudak: "ash",
  dub: "oak",
  dwaejipul: "ragweed",
  ebirch: "birch",
  eg: "oak",
  eger: "alder",
  ehesl: "hazel",
  eiche: "oak",
  eik: "oak",
  ek: "oak",
  elia: "olive",
  els: "alder",
  eoledor: "alder",
  erle: "alder",
  es: "ash",
  esche: "ash",
  fekete_urom: "mugwort",
  fenyo: "pine",
  findik_agaci: "hazel",
  foyntoykia: "hazel",
  frasin: "ash",
  frassino: "ash",
  frene: "ash",
  fresno: "ash",
  furu: "pine",
  fyr: "pine",
  ganlanshu: "olive",
  gddi: "grass",
  grabo: "mugwort",
  grabynke: "mugwort",
  graminees: "grass",
  graser: "grass",
  grassen: "grass",
  grasses: "grass",
  hakoyanagi: "poplar",
  hannoki: "alder",
  haselnuss: "hazel",
  hashibami: "hazel",
  hassel: "hazel",
  hazelaar: "hazel",
  hecl: "hazel",
  heijeulnamu: "hazel",
  hej_l: "hazel",
  hejel_mokk: "hazel",
  hejhel: "hazel",
  hejhl: "hazel",
  hesl: "hazel",
  htti_mr: "poplar",
  huashu: "birch",
  hulluglu: "grass",
  hus_agaci: "birch",
  hyajel: "hazel",
  ilbon_samnamu: "cypress",
  inekenozhiwu: "grass",
  j_aitun: "olive",
  jaipnij_sidr: "cypress",
  jajagnamu: "birch",
  japan_cedrus: "cypress",
  japanese_cedar: "cypress",
  japani_sidar: "cypress",
  japanijh_devdar: "cypress",
  japaninsetri: "cypress",
  japanse_ceder: "cypress",
  japanseder: "cypress",
  japansk_ceder: "cypress",
  japansk_cedertrae: "cypress",
  japon_sedir_agaci: "cypress",
  japonsky_ceder: "cypress",
  jappnis_cetar: "cypress",
  jappnis_sidr: "cypress",
  jasan: "ash",
  jasen: "ash",
  jelsa: "alder",
  jesion: "ash",
  jpani_sidr: "cypress",
  jpanis_sidr: "cypress",
  jpnis_sidr: "cypress",
  jr_lm: "alder",
  kabanoki: "birch",
  kanarya_otu: "ragweed",
  kapas: "poplar",
  katnvud: "poplar",
  kattnvut: "poplar",
  kavak: "poplar",
  kedros_iaponias: "cypress",
  khottonwud: "poplar",
  kiefer: "pine",
  kizilagac: "alder",
  koivu: "birch",
  koris: "ash",
  kotnvud: "poplar",
  kpas: "poplar",
  kriptomeriya: "cypress",
  kryptomeria_japonska: "cypress",
  kryptomerie_japonska: "cypress",
  ktnud: "poplar",
  lblwt: "oak",
  lbndq: "hazel",
  lbtwl: "birch",
  leppa: "alder",
  leszczyna: "hazel",
  levithochorto: "mugwort",
  leyka: "poplar",
  lhwr: "poplar",
  lieska: "hazel",
  lishchina: "hazel",
  liska: "hazel",
  lmrn: "ash",
  lrghyd: "ragweed",
  lshyh_ldrj: "mugwort",
  lsnwbr: "pine",
  lzytwn: "olive",
  magort: "mugwort",
  makok: "olive",
  malortsambrosia: "ragweed",
  malurt: "mugwort",
  manty: "pine",
  maslin: "olive",
  matsu: "pine",
  melia: "ash",
  mese: "oak",
  mesteacan: "birch",
  mgvart: "mugwort",
  mgvhrt: "mugwort",
  mgvort: "mugwort",
  mgvortt: "mugwort",
  mgvrt: "mugwort",
  mianbaiyang: "poplar",
  milunamu: "poplar",
  misk_otu: "mugwort",
  mkvort: "mugwort",
  mogyoro: "hazel",
  mulpulenamu: "ash",
  ngai_cuu: "mugwort",
  nocciolo: "hazel",
  noisetier: "hazel",
  nyirfa: "birch",
  ok: "oak",
  ok_mokk: "oak",
  okk: "oak",
  oku: "oak",
  ol_kha: "alder",
  olcha: "alder",
  oldr: "alder",
  oliivi: "olive",
  olijfboom: "olive",
  olinamu: "alder",
  oliv: "olive",
  oliva: "olive",
  oliveira: "olive",
  oliven: "olive",
  olivenbaum: "olive",
  olivh: "olive",
  olivier: "olive",
  olivkove_derevo: "olive",
  olivkovoe_derevo: "olive",
  olivo: "olive",
  olivovnik: "olive",
  oliwka: "olive",
  ollibeunamu: "olive",
  olse: "alder",
  ontano: "alder",
  ook: "oak",
  or: "alder",
  orekh: "hazel",
  oribu: "olive",
  pahkinapensas: "hazel",
  pain: "pine",
  pain_mokk: "pine",
  palina: "mugwort",
  pappel: "poplar",
  parlagfu: "ragweed",
  pelin: "mugwort",
  pelynek: "mugwort",
  peuplier: "poplar",
  peyko: "pine",
  piante_erbacee: "grass",
  pijnboom: "pine",
  pin: "pine",
  pinheiro: "pine",
  pino: "pine",
  pinus: "pine",
  pioppo: "poplar",
  pirc: "birch",
  plante_erbacee: "grass",
  plop: "poplar",
  polin: "mugwort",
  polyn: "mugwort",
  poppel: "poplar",
  poppeli: "poplar",
  pruttimrm: "poplar",
  pujo: "mugwort",
  pullukl: "grass",
  purkl: "grass",
  qimu: "alder",
  quercia: "oak",
  raguid: "ragweed",
  ragvid: "ragweed",
  ragvid_mokk: "ragweed",
  raigvid: "ragweed",
  rakvit: "ragweed",
  regvid: "ragweed",
  rgvid: "ragweed",
  ribenxuesong: "cypress",
  roble: "oak",
  rodel: "alder",
  ruohot: "grass",
  rz_ybny: "cypress",
  saarni: "ash",
  seiyoutoneriko: "ash",
  sicheltanne: "cypress",
  simyda: "birch",
  sn: "pine",
  sonamu: "pine",
  songshu: "pine",
  sosna: "pine",
  ssug: "mugwort",
  stejar: "oak",
  sugi: "cypress",
  tall: "pine",
  tammi: "oak",
  tasneira: "ragweed",
  tnsidaryipun: "cypress",
  tolgy: "oak",
  topol: "poplar",
  topol_trekhgrannyy: "poplar",
  topola: "poplar",
  topolya: "poplar",
  trn_vnspti: "grass",
  tuncao: "ragweed",
  tuoksukki: "ragweed",
  udimr: "ash",
  ulivo: "olive",
  velanidia: "oak",
  vil_kha: "alder",
  xiangshu: "oak",
  yapons_kiy_kedr: "cypress",
  yas: "ash",
  yasen: "ash",
  yomogi: "mugwort",
  zaitun: "olive",
  zeytin: "olive",
  zhenshu: "hazel",
  // GRAMINALES plant aliases for languages where GRASS category and GRAMINALES
  // plant share the same display_name (collision fallback needs these).
  // These slugs also exist in GP_CATEGORY_MAP -> grass_cat; the plant alias
  // is used by the collision handler when the category slot is already taken.
  cao: "grass",
  cimen: "grass",
  co: "grass",
  erba: "grass",
  fu: "grass",
  graes: "grass",
  grama: "grass",
  gramineas: "grass",
  grasidi: "grass",
  gress: "grass",
  gvt: "grass",
  herbacee: "grass",
  hullu: "grass",
  hya: "grass",
  iarba: "grass",
  jandi: "grass",
  pccik: "grass",
  pul: "grass",
  pull: "grass",
  rumput: "grass",
  ruoho: "grass",
  shb: "grass",
  trava: "grass",
  travy: "grass",
  trawy: "grass",
};

// Merged map: computed from per-adapter aliases (order matches legacy map).
export const ALLERGEN_TRANSLATION = {
  ...PP_ALIASES,
  ...DWD_ALIASES,
  ...PEU_ALIASES,
  ...KLEENEX_ALIASES,
  ...PLU_ALIASES,
  ...ATMO_ALIASES,
  ...GPL_ALIASES,
  ...GP_ALIASES,
};

/**
 * Resolve a raw allergen slug to its canonical key.
 * Returns the canonical key if found, otherwise the input unchanged.
 */
export function toCanonicalAllergenKey(raw) {
  return ALLERGEN_TRANSLATION[raw] || raw;
}

// Icon fallback mapping for allergens that don't have their own icons
export const ALLERGEN_ICON_FALLBACK = {
  trees_cat: "birch", // Use birch icon for trees category
  grass_cat: "grass", // Use grass icon for grass category
  weeds_cat: "mugwort", // Use mugwort icon for weeds category
  trees: "birch", // Keep original for compatibility
  weeds: "mugwort", // Keep original for compatibility
  // grass has its own icon, no fallback needed
  // Google Pollen Levels fallbacks
  cottonwood: "poplar",
  juniper: "cypress",
  japanese_cedar: "cypress",
  japanese_cypress: "cypress",
  graminales: "grass",
  cypress_pine: "cypress",
  maple: "oak",
};

// Mapping of localized category name prefixes to canonical names for Kleenex integration
// The Kleenex integration creates sensors with localized category names based on HA language
// Using prefixes to handle both singular and plural forms (e.g., onkruid/onkruiden)
export const KLEENEX_LOCALIZED_CATEGORY_NAMES = {
  // English
  tree: "trees", // matches trees
  grass: "grass",
  weed: "weeds", // matches weeds
  // Dutch
  bomen: "trees",
  gras: "grass",
  onkruid: "weeds", // matches both onkruid and onkruiden
  kruid: "weeds", // matches kruid and kruiden
  // French
  arbre: "trees", // matches arbres
  graminee: "grass", // matches graminees, graminées
  herbacee: "weeds", // matches herbacees, herbacées
  // Italian
  alber: "trees", // matches alberi
  graminace: "grass", // matches graminacee
  erbace: "weeds", // matches erbacee
};

export const PP_POSSIBLE_CITIES = [
  "Borlänge",
  "Bräkne-Hoby",
  "Eskilstuna",
  "Forshaga",
  "Gävle",
  "Göteborg",
  "Hässleholm",
  "Jönköping",
  "Kristianstad",
  "Ljusdal",
  "Malmö",
  "Norrköping",
  "Nässjö",
  "Piteå",
  "Skövde",
  "Stockholm",
  "Storuman",
  "Sundsvall",
  "Umeå",
  "Visby",
  "Västervik",
  "Östersund",
];

export const COSMETIC_FIELDS = [
  "icon_size",
  "icon_color_mode",
  "icon_color",
  "allergen_color_mode",
  "allergen_colors",
  "allergen_outline_color",
  "allergen_stroke_width",
  "allergen_stroke_color_synced",
  "allergen_levels_gap_synced",
  "levels_inherit_mode",
  "background_color",
  "levels_colors",
  "levels_empty_color",
  "levels_gap_color",
  "levels_thickness",
  "levels_gap",
  "levels_text_color",
  "levels_text_size",
  "levels_icon_ratio",
  "levels_text_weight",
  "minimal",
  "show_text_allergen",
  "show_value_text",
  "show_value_numeric",
  "show_value_numeric_in_circle",
  "allergens_abbreviated",
  "days_boldfaced",
  "text_size_ratio",
  "minimal_gap",
  "show_block_separator",
  "title",
  "card_mod",
];
