// src/constants.js

export const DWD_REGIONS = {
  11: "Schleswig-Holstein und Hamburg",
  12: "Schleswig-Holstein und Hamburg",
  20: "Mecklenburg-Vorpommern",
  31: "Niedersachsen und Bremen",
  32: "Niedersachsen und Bremen",
  41: "Nordrhein-Westfalen",
  42: "Nordrhein-Westfalen",
  43: "Nordrhein-Westfalen",
  50: "Brandenburg und Berlin",
  61: "Sachsen-Anhalt",
  62: "Sachsen-Anhalt",
  71: "Thüringen",
  72: "Thüringen",
  81: "Sachsen",
  82: "Sachsen",
  91: "Hessen",
  92: "Hessen",
  101: "Rheinland-Pfalz und Saarland",
  102: "Rheinland-Pfalz und Saarland",
  103: "Rheinland-Pfalz und Saarland",
  111: "Baden-Württemberg",
  112: "Baden-Württemberg",
  113: "Baden-Württemberg",
  121: "Bayern",
  122: "Bayern",
  123: "Bayern",
  124: "Bayern",
};

// Per-adapter allergen alias maps.
// Each maps raw/localized allergen slugs to canonical keys.
// The global ALLERGEN_TRANSLATION is computed from these at the bottom.

const PP_ALIASES = {
  al: "alder",
  alm: "elm",
  bok: "beech",
  bjork: "birch",
  ek: "oak",
  grabo: "mugwort",
  gras: "grass",
  hassel: "hazel",
  malortsambrosia: "ragweed",
  salg_och_viden: "willow",
};

const DWD_ALIASES = {
  erle: "alder",
  ambrosia: "ragweed",
  esche: "ash",
  birke: "birch",
  buche: "beech",
  hasel: "hazel",
  graser: "grass",
  graeser: "grass",
  beifuss: "mugwort",
  roggen: "rye",
};

const PEU_ALIASES = {
  olive: "olive",
  plane: "plane",
  cypress: "cypress",
  lime: "lime",
  mold_spores: "mold_spores",
  nettle_and_pellitory: "nettle_and_pellitory",
  fungal_spores: "mold_spores",
  grasses: "grass",
  cypress_family: "cypress",
  nettle_family: "nettle_and_pellitory",
  plane_tree: "plane",
  rye: "rye",
  ragweed: "ragweed",
  birch: "birch",
  alder: "alder",
  hazel: "hazel",
  mugwort: "mugwort",
  allergy_risk: "allergy_risk",
  index: "allergy_risk",
};

const KLEENEX_ALIASES = {
  pine: "pine",
  poplar: "poplar",
  poaceae: "poaceae",
  chenopod: "chenopod",
  nettle: "nettle",
  grass_cat: "grass_cat",
  trees_cat: "trees_cat",
  weeds_cat: "weeds_cat",
};

const PLU_ALIASES = {
  sorrel: "sorrel",
  rumex: "sorrel",
  ampfer: "sorrel",
  oseille: "sorrel",
  artemisia: "mugwort",
  betula: "birch",
  bouleau: "birch",
  fagus: "beech",
  hetre: "beech",
  hetra: "beech",
  quercus: "oak",
  eiche: "oak",
  chene: "oak",
  alnus: "alder",
  aulne: "alder",
  fraxinus: "ash",
  frene: "ash",
  chenopodium: "goosefoot",
  goosefoot: "goosefoot",
  gaensefuss: "goosefoot",
  gansefuss: "goosefoot",
  chenopode: "goosefoot",
  poacea: "poaceae",
  graminees: "poaceae",
  corylus: "hazel",
  haselnussstrauch: "hazel",
  noisetier: "hazel",
  plantago: "plantain",
  plantain: "plantain",
  wegerich: "plantain",
  armoise: "mugwort",
};

const ATMO_ALIASES = {
  ambroisie: "ragweed",
  gramine: "grass",
  olivier: "olive",
  pm25: "pm25",
  pm10: "pm10",
  ozone: "ozone",
  no2: "no2",
  so2: "so2",
  dioxyde_d_azote: "no2",
  dioxyde_de_soufre: "so2",
  qualite_globale: "qualite_globale",
};

const GPL_ALIASES = {
  cottonwood: "poplar",
  juniper: "cypress",
  japanese_cedar: "cypress",
  japanese_cypress: "cypress",
  graminales: "grass",
  cypress_pine: "cypress",
};

// GP (svenove/home-assistant-google-pollen) slugified display_name aliases.
// Auto-generated from the Google Pollen API for 35 supported languages
// by scripts/fetch-gp-translations.js. Some entries overlap with other
// adapter alias maps; that is harmless since all are merged.
// Auto-generated from the Google Pollen API for 35 languages
// by scripts/fetch-gp-translations.js using the card's own slugify().
// Non-Latin scripts (ar, bn, el, gu, hi, ja, kn, ko, ml, mr, ta, te, th, zh)
// slugify to "unknown" and require unique_id-based classification instead.
const GP_ALIASES = {
  abedul: "birch",
  aliso: "alder",
  alun: "hazel",
  ambroz_ia: "ragweed",
  ambrozia: "ragweed",
  ambrozie: "ragweed",
  ambroziia: "ragweed",
  ambrozja: "ragweed",
  amerikai_nyar: "poplar",
  amieiro: "alder",
  arin: "alder",
  ask: "ash",
  aveleira: "hazel",
  avellano: "hazel",
  beifus: "mugwort",
  beiskambrosia: "ragweed",
  bereza: "birch",
  berk: "birch",
  betulla: "birch",
  bijvoet: "mugwort",
  birk: "birch",
  birke: "birch",
  borovica: "pine",
  borovice: "pine",
  breza: "birch",
  briza: "birch",
  brzoza: "birch",
  bylica: "mugwort",
  bynkeambrosie: "ragweed",
  c_ph_n_h_ng: "ragweed",
  cam: "pine",
  carvalho: "oak",
  cay_b_ch_d_ng: "birch",
  cay_d_ng_tia: "alder",
  cay_g_d_ng: "poplar",
  cay_li_u_sam_nh_t: "cypress",
  cay_oliu: "olive",
  cay_ph: "hazel",
  cay_s_i: "oak",
  cay_t_n_bi: "ash",
  cay_thong: "pine",
  cedar_jepang: "cypress",
  cedre_du_japon: "cypress",
  cedro_giapponese: "cypress",
  cedro_japones: "cypress",
  cedru_japonez: "cypress",
  chopo: "poplar",
  choupos: "poplar",
  cim: "grass",
  cottonwood: "poplar",
  cypress_pine: "cypress",
  dab: "oak",
  disbudak: "ash",
  dub: "oak",
  eg: "oak",
  eger: "alder",
  eiche: "oak",
  eik: "oak",
  els: "alder",
  es: "ash",
  esche: "ash",
  fekete_urom: "mugwort",
  fenyo: "pine",
  findik_agaci: "hazel",
  frasin: "ash",
  frassino: "ash",
  fresno: "ash",
  furu: "pine",
  fyr: "pine",
  grabynke: "mugwort",
  grassen: "grass",
  grasses: "grass",
  haselnuss: "hazel",
  hazelaar: "hazel",
  hus_agaci: "birch",
  iaponskij_kedr: "cypress",
  iasen: "ash",
  japan_cedrus: "cypress",
  japanese_cedar: "cypress",
  japaninsetri: "cypress",
  japanse_ceder: "cypress",
  japanseder: "cypress",
  japansk_ceder: "cypress",
  japansk_cedertra: "cypress",
  japon_sedir_agaci: "cypress",
  japonsky_ceder: "cypress",
  jasan: "ash",
  jasen: "ash",
  jelsa: "alder",
  jesion: "ash",
  kanarya_otu: "ragweed",
  kapas: "poplar",
  kavak: "poplar",
  kiefer: "pine",
  kizilagac: "alder",
  koivu: "birch",
  koris: "ash",
  kriptomeriia: "cypress",
  kryptomeria_japonska: "cypress",
  kryptomerie_japonska: "cypress",
  l_shchina: "hazel",
  leppa: "alder",
  leszczyna: "hazel",
  lieska: "hazel",
  liska: "hazel",
  malurt: "mugwort",
  manty: "pine",
  maslin: "olive",
  mese: "oak",
  mesteacan: "birch",
  misk_otu: "mugwort",
  mogyoro: "hazel",
  ng_i_c_u: "mugwort",
  nocciolo: "hazel",
  nyirfa: "birch",
  olcha: "alder",
  olha: "alder",
  oliivi: "olive",
  olijfboom: "olive",
  oliv: "olive",
  oliva: "olive",
  oliveira: "olive",
  oliven: "olive",
  olivenbaum: "olive",
  olivkove_derevo: "olive",
  olivkovoe_derevo: "olive",
  olivo: "olive",
  olivovnik: "olive",
  oliwka: "olive",
  olse: "alder",
  ontano: "alder",
  or: "alder",
  oreh: "hazel",
  pahkinapensas: "hazel",
  palina: "mugwort",
  pappel: "poplar",
  parlagfu: "ragweed",
  pelin: "mugwort",
  pelynek: "mugwort",
  peuplier: "poplar",
  piante_erbacee: "grass",
  pijnboom: "pine",
  pin: "pine",
  pinheiro: "pine",
  pino: "pine",
  pinus: "pine",
  pioppo: "poplar",
  plante_erbacee: "grass",
  plop: "poplar",
  polin: "mugwort",
  polyn: "mugwort",
  poppel: "poplar",
  poppeli: "poplar",
  pujo: "mugwort",
  quercia: "oak",
  roble: "oak",
  rodel: "alder",
  ruohot: "grass",
  saarni: "ash",
  sicheltanne: "cypress",
  sosna: "pine",
  stejar: "oak",
  tall: "pine",
  tammi: "oak",
  tasneira: "ragweed",
  tolgy: "oak",
  topo: "poplar",
  topol: "poplar",
  topol_trehgrannyj: "poplar",
  topola: "poplar",
  topolia: "poplar",
  tuoksukki: "ragweed",
  ulivo: "olive",
  v_lha: "alder",
  zaitun: "olive",
  zeytin: "olive",
};

// Merged map: computed from per-adapter aliases (order matches legacy map).
export const ALLERGEN_TRANSLATION = {
  ...PP_ALIASES,
  ...DWD_ALIASES,
  ...PEU_ALIASES,
  ...KLEENEX_ALIASES,
  ...PLU_ALIASES,
  ...ATMO_ALIASES,
  ...GPL_ALIASES,
  ...GP_ALIASES,
};

/**
 * Resolve a raw allergen slug to its canonical key.
 * Returns the canonical key if found, otherwise the input unchanged.
 */
export function toCanonicalAllergenKey(raw) {
  return ALLERGEN_TRANSLATION[raw] || raw;
}

// Icon fallback mapping for allergens that don't have their own icons
export const ALLERGEN_ICON_FALLBACK = {
  trees_cat: "birch", // Use birch icon for trees category
  grass_cat: "grass", // Use grass icon for grass category
  weeds_cat: "mugwort", // Use mugwort icon for weeds category
  trees: "birch", // Keep original for compatibility
  weeds: "mugwort", // Keep original for compatibility
  // grass has its own icon, no fallback needed
  // Google Pollen Levels fallbacks
  cottonwood: "poplar",
  juniper: "cypress",
  japanese_cedar: "cypress",
  japanese_cypress: "cypress",
  graminales: "grass",
  cypress_pine: "cypress",
  maple: "oak",
};

// Mapping of localized category name prefixes to canonical names for Kleenex integration
// The Kleenex integration creates sensors with localized category names based on HA language
// Using prefixes to handle both singular and plural forms (e.g., onkruid/onkruiden)
export const KLEENEX_LOCALIZED_CATEGORY_NAMES = {
  // English
  tree: "trees", // matches trees
  grass: "grass",
  weed: "weeds", // matches weeds
  // Dutch
  bomen: "trees",
  gras: "grass",
  onkruid: "weeds", // matches both onkruid and onkruiden
  kruid: "weeds", // matches kruid and kruiden
  // French
  arbre: "trees", // matches arbres
  graminee: "grass", // matches graminees, graminées
  herbacee: "weeds", // matches herbacees, herbacées
  // Italian
  alber: "trees", // matches alberi
  graminace: "grass", // matches graminacee
  erbace: "weeds", // matches erbacee
};

export const PP_POSSIBLE_CITIES = [
  "Borlänge",
  "Bräkne-Hoby",
  "Eskilstuna",
  "Forshaga",
  "Gävle",
  "Göteborg",
  "Hässleholm",
  "Jönköping",
  "Kristianstad",
  "Ljusdal",
  "Malmö",
  "Norrköping",
  "Nässjö",
  "Piteå",
  "Skövde",
  "Stockholm",
  "Storuman",
  "Sundsvall",
  "Umeå",
  "Visby",
  "Västervik",
  "Östersund",
];

export const COSMETIC_FIELDS = [
  "icon_size",
  "icon_color_mode",
  "icon_color",
  "allergen_color_mode",
  "allergen_colors",
  "allergen_outline_color",
  "allergen_stroke_width",
  "allergen_stroke_color_synced",
  "allergen_levels_gap_synced",
  "levels_inherit_mode",
  "background_color",
  "levels_colors",
  "levels_empty_color",
  "levels_gap_color",
  "levels_thickness",
  "levels_gap",
  "levels_text_color",
  "levels_text_size",
  "levels_icon_ratio",
  "levels_text_weight",
  "minimal",
  "show_text_allergen",
  "show_value_text",
  "show_value_numeric",
  "show_value_numeric_in_circle",
  "allergens_abbreviated",
  "days_boldfaced",
  "text_size_ratio",
  "minimal_gap",
  "show_block_separator",
  "title",
  "card_mod",
];
