// src/adapters/gp/constants.js
import { LEVELS_DEFAULTS } from "../../utils/levels-defaults.js";

// Domain used by svenove/home-assistant-google-pollen
export const GP_DOMAIN = "google_pollen";

// Map slugified category display_names to canonical category keys.
// Auto-generated from the Google Pollen API for 35 supported languages
// by scripts/fetch-gp-translations.js using the card's own slugify().
// Non-Latin scripts are now properly transliterated via any-ascii.
export const GP_CATEGORY_MAP = {
  agac: "trees_cat",
  agacha: "weeds_cat",
  agriochorto: "weeds_cat",
  alberi: "trees_cat",
  arbol: "trees_cat",
  arbore: "trees_cat",
  arbre: "trees_cat",
  arvore: "trees_cat",
  baume: "trees_cat",
  bomen: "trees_cat",
  bur_yan: "weeds_cat",
  burina: "weeds_cat",
  buruieni: "weeds_cat",
  cao: "grass_cat",
  cay: "trees_cat",
  cettu: "trees_cat",
  chwasty: "weeds_cat",
  cimen: "grass_cat",
  co: "grass_cat",
  co_dai: "weeds_cat",
  dentro: "trees_cat",
  derevo: "trees_cat",
  drzewa: "trees_cat",
  erba: "grass_cat",
  erbacce: "weeds_cat",
  ervas: "weeds_cat",
  fa: "trees_cat",
  fu: "grass_cat",
  gach: "trees_cat",
  ghas: "weeds_cat",
  graes: "grass_cat",
  graesser: "weeds_cat",
  grama: "grass_cat",
  gramineas: "grass_cat",
  gras: "grass_cat",
  grasidi: "grass_cat",
  grass: "grass_cat",
  gress: "grass_cat",
  gulma: "weeds_cat",
  gvt: "grass_cat",
  gyomnoveny: "weeds_cat",
  heinakasvit: "weeds_cat",
  herbacee: "grass_cat",
  herbacees: "weeds_cat",
  hullu: "grass_cat",
  hya: "grass_cat",
  iarba: "grass_cat",
  jabcho: "weeds_cat",
  jandi: "grass_cat",
  jhad: "trees_cat",
  kl: "weeds_cat",
  klai: "weeds_cat",
  kle: "weeds_cat",
  klupumokklu: "weeds_cat",
  l_shb_ldrh: "weeds_cat",
  maleza: "weeds_cat",
  mr: "trees_cat",
  mrm: "trees_cat",
  mu: "trees_cat",
  namu: "trees_cat",
  nimdn: "weeds_cat",
  ogras: "weeds_cat",
  onkruid: "weeds_cat",
  pccik: "grass_cat",
  ped: "trees_cat",
  plevelne_rostliny: "weeds_cat",
  pohon: "trees_cat",
  pul: "grass_cat",
  pull: "grass_cat",
  puu: "trees_cat",
  rumput: "grass_cat",
  ruoho: "grass_cat",
  shb: "grass_cat",
  shjrh: "trees_cat",
  shu: "trees_cat",
  sornyaki: "weeds_cat",
  stromy: "trees_cat",
  tn: "weeds_cat",
  tnaim: "trees_cat",
  trad: "trees_cat",
  trae: "trees_cat",
  trava: "grass_cat",
  travy: "grass_cat",
  trawy: "grass_cat",
  tre: "trees_cat",
  tree: "trees_cat",
  ugress: "weeds_cat",
  unkraut: "weeds_cat",
  vrks: "trees_cat",
  wachphuech: "weeds_cat",
  weed: "weeds_cat",
  yabanci_ot: "weeds_cat",
  zacao: "weeds_cat",
};

// Base allergens (categories) always available
export const GP_BASE_ALLERGENS = ["grass_cat", "trees_cat", "weeds_cat"];

export const stubConfigGP = {
  integration: "gp",
  location: "",
  entity_prefix: "",
  entity_suffix: "",
  allergens: ["grass_cat", "trees_cat", "weeds_cat"],
  minimal: false,
  minimal_gap: 35,
  background_color: "",
  icon_size: "48",
  text_size_ratio: 1,
  ...LEVELS_DEFAULTS,
  show_text_allergen: true,
  show_value_text: true,
  show_value_numeric: false,
  show_value_numeric_in_circle: false,
  show_empty_days: false,
  debug: false,
  show_version: true,
  days_to_show: 4,
  days_relative: true,
  days_abbreviated: false,
  days_uppercase: false,
  days_boldfaced: false,
  pollen_threshold: 1,
  sort: "value_descending",
  sort_category_allergens_first: true,
  allergens_abbreviated: false,
  link_to_sensors: true,
  date_locale: undefined,
  title: undefined,
  phrases: { full: {}, short: {}, levels: [], days: {}, no_information: "" },
};

export function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
