// src/adapters/gp/constants.js
import { LEVELS_DEFAULTS } from "../../utils/levels-defaults.js";

// Domain used by svenove/home-assistant-google-pollen
export const GP_DOMAIN = "google_pollen";

// Map raw display_name (trimmed, lowercased) to canonical allergen/category keys.
// Generated from the Google Pollen API for 35 supported languages
// by scripts/fetch-gp-translations.js. Uses direct string lookup instead of
// slugify, so no transliteration dependency is needed at runtime.
// 478 entries across 35 languages (+ manual additions for rare plant types)
export const GP_DISPLAY_NAME_MAP = {
  // Manual additions: English display_names for plant types not returned by
  // the API for Berlin/Tokyo (the script's query locations), but present in
  // svenove's PLANT_TYPES list and potentially returned for other regions.
  "cypress pine": "cypress_pine",
  "elm": "elm",
  "graminales": "graminales",
  "juniper": "juniper",
  "maple": "maple",
  "abedul": "birch",
  "ağaç": "trees_cat",
  "al": "alder",
  "alberi": "trees_cat",
  "alder": "alder",
  "aliso": "alder",
  "alun": "hazel",
  "ambroisie": "ragweed",
  "ambrosia": "ragweed",
  "ambrosía": "ragweed",
  "ambrózia": "ragweed",
  "ambrozie": "ragweed",
  "ambrózie": "ragweed",
  "ambrozja": "ragweed",
  "amerikai nyár": "cottonwood",
  "amieiro": "alder",
  "árbol": "trees_cat",
  "arbore": "trees_cat",
  "arbre": "trees_cat",
  "arin": "alder",
  "armoise": "mugwort",
  "artemisia": "mugwort",
  "artemísia": "mugwort",
  "artemisia comune": "mugwort",
  "árvore": "trees_cat",
  "ash": "ash",
  "ask": "ash",
  "aulne": "alder",
  "aveleira": "hazel",
  "avellano": "hazel",
  "beifuß": "mugwort",
  "beiskambrosia": "ragweed",
  "berk": "birch",
  "bétula": "birch",
  "betulla": "birch",
  "bijvoet": "mugwort",
  "birch": "birch",
  "birk": "birch",
  "birke": "birch",
  "björk": "birch",
  "bjørk": "birch",
  "bomen": "trees_cat",
  "borovica": "pine",
  "borovice": "pine",
  "bouleau": "birch",
  "breza": "birch",
  "bříza": "birch",
  "brzoza": "birch",
  "burina": "weeds_cat",
  "buruieni": "weeds_cat",
  "bylica": "mugwort",
  "bynkeambrosie": "ragweed",
  "bäume": "trees_cat",
  "çam": "pine",
  "carvalho": "oak",
  "cây": "trees_cat",
  "cây bạch dương": "birch",
  "cây dương tía": "alder",
  "cây gỗ dương": "cottonwood",
  "cây liễu sam nhật": "japanese_cedar",
  "cây phỉ": "hazel",
  "cây sồi": "oak",
  "cây tần bì": "ash",
  "cây thông": "pine",
  "cây ôliu": "olive",
  "cedar jepang": "japanese_cedar",
  "cèdre du japon": "japanese_cedar",
  "cedro giapponese": "japanese_cedar",
  "cedro japonés": "japanese_cedar",
  "cedro japonês": "japanese_cedar",
  "cedru japonez": "japanese_cedar",
  "chêne": "oak",
  "chopo": "cottonwood",
  "choupos": "cottonwood",
  "chwasty": "weeds_cat",
  "çim": "graminales",
  "çimen": "grass_cat",
  "cỏ": "grass_cat",
  "cỏ dại": "weeds_cat",
  "cỏ phấn hương": "ragweed",
  "cottonwood": "cottonwood",
  "dąb": "oak",
  "dişbudak": "ash",
  "drzewa": "trees_cat",
  "dub": "oak",
  "eg": "oak",
  "éger": "alder",
  "eiche": "oak",
  "eik": "oak",
  "ek": "oak",
  "els": "alder",
  "erba": "grass_cat",
  "erbacce": "weeds_cat",
  "erle": "alder",
  "ervas": "weeds_cat",
  "es": "ash",
  "esche": "ash",
  "fa": "trees_cat",
  "fekete üröm": "mugwort",
  "fenyő": "pine",
  "fındık ağacı": "hazel",
  "frasin": "ash",
  "frassino": "ash",
  "frêne": "ash",
  "fresno": "ash",
  "furu": "pine",
  "fű": "grass_cat",
  "fyr": "pine",
  "grama": "grass_cat",
  "gramíneas": "grass_cat",
  "graminées": "graminales",
  "gras": "grass_cat",
  "grass": "grass_cat",
  "grassen": "graminales",
  "grasses": "graminales",
  "gress": "grass_cat",
  "gråbo": "mugwort",
  "gråbynke": "mugwort",
  "gräs": "grass_cat",
  "græs": "grass_cat",
  "gräser": "graminales",
  "græsser": "weeds_cat",
  "gulma": "weeds_cat",
  "gyomnövény": "weeds_cat",
  "haselnuss": "hazel",
  "hassel": "hazel",
  "hazel": "hazel",
  "hazelaar": "hazel",
  "heinäkasvit": "weeds_cat",
  "herbacée": "grass_cat",
  "herbacées": "weeds_cat",
  "huş ağacı": "birch",
  "iarbă": "grass_cat",
  "japán cédrus": "japanese_cedar",
  "japanese cedar": "japanese_cedar",
  "japaninsetri": "japanese_cedar",
  "japanse ceder": "japanese_cedar",
  "japanseder": "japanese_cedar",
  "japansk ceder": "japanese_cedar",
  "japansk cedertræ": "japanese_cedar",
  "japon sedir ağacı": "japanese_cedar",
  "japonský céder": "japanese_cedar",
  "jasan": "ash",
  "jaseň": "ash",
  "jelša": "alder",
  "jesion": "ash",
  "kanarya otu": "ragweed",
  "kapas": "cottonwood",
  "kavak": "cottonwood",
  "kiefer": "pine",
  "kızılağaç": "alder",
  "koivu": "birch",
  "kryptomeria japońska": "japanese_cedar",
  "kryptomérie japonská": "japanese_cedar",
  "kőris": "ash",
  "leppä": "alder",
  "leszczyna": "hazel",
  "lieska": "hazel",
  "líska": "hazel",
  "maleza": "weeds_cat",
  "malurt": "mugwort",
  "malörtsambrosia": "ragweed",
  "măslin": "olive",
  "meşe": "oak",
  "mesteacăn": "birch",
  "misk otu": "mugwort",
  "mogyoró": "hazel",
  "mugwort": "mugwort",
  "mänty": "pine",
  "ngải cứu": "mugwort",
  "nocciolo": "hazel",
  "noisetier": "hazel",
  "nyírfa": "birch",
  "oak": "oak",
  "ogräs": "weeds_cat",
  "olcha": "alder",
  "oliivi": "olive",
  "olijfboom": "olive",
  "oliv": "olive",
  "oliva": "olive",
  "olíva": "olive",
  "olive": "olive",
  "oliveira": "olive",
  "oliven": "olive",
  "olivenbaum": "olive",
  "olivier": "olive",
  "olivo": "olive",
  "olivovník": "olive",
  "oliwka": "olive",
  "olše": "alder",
  "onkruid": "weeds_cat",
  "ontano": "alder",
  "or": "alder",
  "palina": "mugwort",
  "pappel": "cottonwood",
  "parlagfű": "ragweed",
  "pelin": "mugwort",
  "pelyněk": "mugwort",
  "peuplier": "cottonwood",
  "piante erbacee": "graminales",
  "pijnboom": "pine",
  "pin": "pine",
  "pine": "pine",
  "pinheiro": "pine",
  "pino": "pine",
  "pinus": "pine",
  "pioppo": "cottonwood",
  "plante erbacee": "graminales",
  "plevelné rostliny": "weeds_cat",
  "plop": "cottonwood",
  "pohon": "trees_cat",
  "poppel": "cottonwood",
  "poppeli": "cottonwood",
  "pujo": "mugwort",
  "puu": "trees_cat",
  "pähkinäpensas": "hazel",
  "quercia": "oak",
  "ragweed": "ragweed",
  "roble": "oak",
  "rumput": "grass_cat",
  "ruoho": "grass_cat",
  "ruohot": "graminales",
  "rødel": "alder",
  "saarni": "ash",
  "sicheltanne": "japanese_cedar",
  "sosna": "pine",
  "stejar": "oak",
  "stromy": "trees_cat",
  "tall": "pine",
  "tammi": "oak",
  "tasneira": "ragweed",
  "topol": "cottonwood",
  "topoľ": "cottonwood",
  "topola": "cottonwood",
  "trávy": "grass_cat",
  "trawy": "grass_cat",
  "tre": "trees_cat",
  "tree": "trees_cat",
  "træ": "trees_cat",
  "träd": "trees_cat",
  "tuoksukki": "ragweed",
  "tölgy": "oak",
  "ugress": "weeds_cat",
  "ulivo": "olive",
  "unkraut": "weeds_cat",
  "weed": "weeds_cat",
  "yabancı ot": "weeds_cat",
  "zaitun": "olive",
  "zeytin": "olive",
  "αγριόχορτο": "weeds_cat",
  "άλνος": "alder",
  "αμβροσία αρτεμισίφυλλος": "ragweed",
  "βελανιδιά": "oak",
  "γρασίδι": "grass_cat",
  "δέντρο": "trees_cat",
  "ελιά": "olive",
  "κέδρος ιαπωνίας": "japanese_cedar",
  "λεβιθόχορτο": "mugwort",
  "λεύκα": "cottonwood",
  "μελιά": "ash",
  "πεύκο": "pine",
  "σημύδα": "birch",
  "φουντουκιά": "hazel",
  "амброзия": "ragweed",
  "амброзія": "ragweed",
  "береза": "birch",
  "бур'ян": "weeds_cat",
  "вільха": "alder",
  "дерево": "trees_cat",
  "дуб": "oak",
  "криптомерия": "japanese_cedar",
  "ліщина": "hazel",
  "оливкове дерево": "olive",
  "оливковое дерево": "olive",
  "ольха": "alder",
  "орех": "hazel",
  "полин": "mugwort",
  "полынь": "mugwort",
  "сорняки": "weeds_cat",
  "сосна": "pine",
  "тополь трехгранный": "cottonwood",
  "тополя": "cottonwood",
  "трава": "grass_cat",
  "травы": "graminales",
  "японський кедр": "japanese_cedar",
  "ясен": "ash",
  "ясень": "ash",
  "أرز ياباني": "japanese_cedar",
  "الأعشاب الضارة": "weeds_cat",
  "البتولا": "birch",
  "البلوط": "oak",
  "البندق": "hazel",
  "الحور": "cottonwood",
  "الرغيد": "ragweed",
  "الزيتون": "olive",
  "الشيح الدارج": "mugwort",
  "الصنوبر": "pine",
  "المران": "ash",
  "جار الماء": "alder",
  "شجرة": "trees_cat",
  "عشب": "grass_cat",
  "अल्डर": "alder",
  "अ‍ॅश": "ash",
  "ऐश": "ash",
  "ऑलिव्ह": "olive",
  "ऑल्डर": "alder",
  "ओक": "oak",
  "कपास": "cottonwood",
  "कॉटनवुड": "cottonwood",
  "गवत": "grass_cat",
  "घास": "weeds_cat",
  "जपानी सिडर": "japanese_cedar",
  "ज़ैतून": "olive",
  "जैपनीज़ सीडर": "japanese_cedar",
  "झाड": "trees_cat",
  "तण": "weeds_cat",
  "तृण वनस्पती": "graminales",
  "देवदार": "pine",
  "पाइन": "pine",
  "पेड़": "trees_cat",
  "बर्च": "birch",
  "मगवर्ट": "mugwort",
  "मगव्हर्ट": "mugwort",
  "रगवीड": "ragweed",
  "रैगवीड": "ragweed",
  "हेज़ल": "hazel",
  "हेझल": "hazel",
  "অলিভ": "olive",
  "অ্যাশ": "ash",
  "আগাছা": "weeds_cat",
  "আল্ডার": "alder",
  "ওক": "oak",
  "কটনউড": "cottonwood",
  "গাছ": "trees_cat",
  "ঘাস": "grass_cat",
  "জাপানি সিডার": "japanese_cedar",
  "পাইন": "pine",
  "বার্চ": "birch",
  "মাগওর্ট": "mugwort",
  "রাগউইড": "ragweed",
  "হ্যাজেল": "hazel",
  "આલ્ડર": "alder",
  "ઍશ": "ash",
  "ઑક": "oak",
  "ઑલિવ": "olive",
  "કૉટનવૂડ": "cottonwood",
  "ઘાસ": "grass_cat",
  "જાપાનીઝ દેવદાર": "japanese_cedar",
  "નીંદણ": "weeds_cat",
  "પાઇન": "pine",
  "બર્ચ": "birch",
  "મગવૉર્ટ": "mugwort",
  "રૅગ્વીડ": "ragweed",
  "વૃક્ષ": "trees_cat",
  "હેઝલ": "hazel",
  "ஆலிவ்": "olive",
  "ஆல்டர்": "alder",
  "ஆஷ்": "ash",
  "ஓக்": "oak",
  "களை": "weeds_cat",
  "காட்டன்வுட்": "cottonwood",
  "பிர்ச்": "birch",
  "புல்": "grass_cat",
  "புற்கள்": "graminales",
  "பைன்": "pine",
  "மக்வோர்ட்": "mugwort",
  "மரம்": "trees_cat",
  "ராக்வீட்": "ragweed",
  "ஜாப்பனீஸ் செடார்": "japanese_cedar",
  "ஹேசல்": "hazel",
  "ఆలివ్ మొక్క": "olive",
  "ఆల్డర్": "alder",
  "ఓక్ మొక్క": "oak",
  "కలుపుమొక్కలు": "weeds_cat",
  "కాటన్‌వుడ్": "cottonwood",
  "గడ్డి": "graminales",
  "చెట్టు": "trees_cat",
  "జపనీస్ సీడర్": "japanese_cedar",
  "పచ్చిక": "grass_cat",
  "పైన్ మొక్క": "pine",
  "బర్చ్": "birch",
  "మగ్‌వార్ట్": "mugwort",
  "యాష్": "ash",
  "రాగ్‌వీడ్ మొక్క": "ragweed",
  "హేజెల్ మొక్క": "hazel",
  "ಆಲಿವ್": "olive",
  "ಆಲ್ಡರ್": "alder",
  "ಉಡಿಮರ": "ash",
  "ಓಕ್": "oak",
  "ಕಳೆ": "weeds_cat",
  "ಜಪಾನೀಸ್ ಸೀಡರ್": "japanese_cedar",
  "ಪೈನ್": "pine",
  "ಬರ್ಚ್": "birch",
  "ಮಗ್ವಾರ್ಟ್": "mugwort",
  "ಮರ": "trees_cat",
  "ರಾಗ್ವೀಡ್": "ragweed",
  "ಹತ್ತಿ ಮರ": "cottonwood",
  "ಹುಲ್ಲು": "grass_cat",
  "ಹುಲ್ಲುಗಳು": "graminales",
  "ಹೇಝೆಲ್": "hazel",
  "ആൽഡർ": "alder",
  "ആഷ്": "ash",
  "ഒലിവ്": "olive",
  "ഓക്ക്": "oak",
  "കള": "weeds_cat",
  "ചന്ദനം": "birch",
  "ജാപ്പനീസ് സീഡർ": "japanese_cedar",
  "പരുത്തിമരം": "cottonwood",
  "പുല്ലുകൾ": "graminales",
  "പുല്ല്": "grass_cat",
  "പൈൻ": "pine",
  "മഗ്‌വോർട്ട്": "mugwort",
  "മരം": "trees_cat",
  "ഹേസൽ": "hazel",
  "റാഗ്‌വീഡ്": "ragweed",
  "คอตตอนวู้ด": "cottonwood",
  "จิงจูฉ่าย": "mugwort",
  "ต้นซีดาร์ญี่ปุ่น": "japanese_cedar",
  "ต้นไม้": "trees_cat",
  "เบิร์ช": "birch",
  "มะกอก": "olive",
  "แร็กวีด": "ragweed",
  "วัชพืช": "weeds_cat",
  "สน": "pine",
  "หญ้า": "grass_cat",
  "เอลเดอร์": "alder",
  "แอช": "ash",
  "โอ๊ก": "oak",
  "เฮเซล": "hazel",
  "나무": "trees_cat",
  "돼지풀": "ragweed",
  "물푸레나무": "ash",
  "미루나무": "cottonwood",
  "소나무": "pine",
  "쑥": "mugwort",
  "오리나무": "alder",
  "올리브나무": "olive",
  "일본 삼나무": "japanese_cedar",
  "자작나무": "birch",
  "잔디": "grass_cat",
  "잡초": "weeds_cat",
  "참나무": "oak",
  "풀": "graminales",
  "헤이즐나무": "hazel",
  "イネ科の植物": "graminales",
  "オーク": "oak",
  "オリーブ": "olive",
  "カバノキ": "birch",
  "スギ": "japanese_cedar",
  "セイヨウトネリコ": "ash",
  "ハコヤナギ": "cottonwood",
  "ハシバミ": "hazel",
  "ハンノキ": "alder",
  "ブタクサ": "ragweed",
  "マツ": "pine",
  "ヨモギ": "mugwort",
  "日本雪松": "japanese_cedar",
  "木": "trees_cat",
  "杂草": "weeds_cat",
  "松树": "pine",
  "树": "trees_cat",
  "桤木": "alder",
  "桦树": "birch",
  "棉白杨": "cottonwood",
  "榛树": "hazel",
  "橄榄树": "olive",
  "橡树": "oak",
  "白蜡树": "ash",
  "艾蒿": "mugwort",
  "草": "grass_cat",
  "草类": "graminales",
  "豚草": "ragweed",
  "雑草": "weeds_cat",
};

// Display names where the GRASS category and the GRAMINALES plant share the same
// display_name string. When a collision is detected during sensor discovery,
// classifySensorAsPlant uses this map to get the plant interpretation.
// 17 entries where GRASS category and GRAMINALES plant share display_name
export const GP_COLLISION_PLANTS = {
  "cỏ": "graminales",
  "fű": "graminales",
  "grama": "graminales",
  "gramíneas": "graminales",
  "gress": "graminales",
  "gräs": "graminales",
  "græs": "graminales",
  "rumput": "graminales",
  "trávy": "graminales",
  "trawy": "graminales",
  "γρασίδι": "graminales",
  "трава": "graminales",
  "عشب": "graminales",
  "घास": "graminales",
  "ঘাস": "graminales",
  "ઘાસ": "graminales",
  "หญ้า": "graminales",
};

// Base allergens (categories) always available
export const GP_BASE_ALLERGENS = ["grass_cat", "trees_cat", "weeds_cat"];

export const stubConfigGP = {
  integration: "gp",
  location: "",
  entity_prefix: "",
  entity_suffix: "",
  allergens: ["grass_cat", "trees_cat", "weeds_cat"],
  minimal: false,
  minimal_gap: 35,
  background_color: "",
  icon_size: "48",
  text_size_ratio: 1,
  ...LEVELS_DEFAULTS,
  show_text_allergen: true,
  show_value_text: true,
  show_value_numeric: false,
  show_value_numeric_in_circle: false,
  show_empty_days: false,
  debug: false,
  show_version: true,
  days_to_show: 4,
  days_relative: true,
  days_abbreviated: false,
  days_uppercase: false,
  days_boldfaced: false,
  pollen_threshold: 1,
  sort: "value_descending",
  sort_category_allergens_first: true,
  allergens_abbreviated: false,
  link_to_sensors: true,
  date_locale: undefined,
  title: undefined,
  phrases: { full: {}, short: {}, levels: [], days: {}, no_information: "" },
};

export function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
